services:

  user:
    build: ./student-image
    networks: [labnet]
    volumes:
      - ./user_home:/home/student
      - ./user_home/.bash_history:/home/student/.bash_history
    restart: always

  wetty_user:
    image: wettyoss/wetty
    environment:
      - SSHHOST=user
      - SSHPORT=22
      - BASE=/user
      - WETTY_COMMAND=login
    networks: [labnet]
    restart: always
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: [labnet]
    restart: always

networks:
  labnet:
    driver: bridge
